SAPR/Models/Purchase.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SAPR.Models
{
    public class Purchase
    {
        public int PurchaseId { get; set; }
        public string Name { get; set; }
        public List<Field> Fields { get; set; }
        public Rule BeforeRule { get; set; }
        public Rule AfterRule { get; set; }
        public ExecutableСode? GeneratedCode { get; set; }
    }
}

SAPR/Controllers/PurchaseController.cs
using Microsoft.AspNetCore.Builder.Extensions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
//using RuleCompiller;
using SAPR.Models;
using SAPR.Utils;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;
using System.Xml.Linq;
using System.Xml.XPath;

namespace SAPR.Controllers
{
    public class PurchaseController : Controller
    {
        private readonly ILogger<PurchaseController> _logger;
        private readonly AppOptions _appOptions;

        DataBaseContext db;
        public PurchaseController(DataBaseContext context, IOptions<AppOptions> appOptions)
        {
            _appOptions = appOptions.Value;
            db = context;
            if (db.Purchases.ToList().Count == 0)
            {
                Purchase purchase1 = new Purchase()
                {
                    Name = "Заявка на получние нового ИНН",
                    Fields = new List<Field>
                    {
                        new Field
                        {
                            Name = "Name",
                            Alias = "Имя",
                            DefaultValue = ""
                        },
                        new Field
                        {
                            Name = "Age",
                            Alias = "Возраст",
                            DefaultValue = ""
                        }
                    },
                    BeforeRule = new Rule()
                    {
                        PurchaseId = 1,
                        Stage = "before",
                        RuleText = ""
                    },
                    AfterRule = new Rule()
                    {
                        PurchaseId = 1,
                        Stage = "after",
                        RuleText = "<rules>" +
                                        "<rule type=\"validation\">" +
                                            "field name=\"Name\" required=\"true\" isRequiredErrorMessage=\"Поле Имя должно быть заполненным\"/>" +
                                        "</rule>" +
                                    "</rules>"
                    },
                    GeneratedCode = new ExecutableСode
                    {
                        Code=""
                    }
                };
                db.Purchases.Add(purchase1);
                db.SaveChanges();
            }
        }

        public IActionResult Index()
        {
            var huipenis = db.Fields.ToList();
            var kek = db.Purchases.FirstOrDefault();
            return View(db.Purchases.ToList());
        }

        [HttpGet]
        [Route("Purchase/CreatePurchase/{id?}")]
        public IActionResult CreatePurchase(int? id)
        {
            var codes = db.ExecutableСodes.ToList();
            var fields = db.Fields.ToList();
            Purchase purchase = db.Purchases.Where(p => p.PurchaseId == id).FirstOrDefault();

            if (id == null) return RedirectToAction("Index");
            ViewBag.Purchase = purchase;

            if (!Directory.Exists($@"{AppDomain.CurrentDomain.BaseDirectory}\{_appOptions.Directories.GeneratedCode}"))
            {
                Directory.CreateDirectory(@$"{AppDomain.CurrentDomain.BaseDirectory}\{_appOptions.Directories.GeneratedCode}");
            }

            var pathGenerateCode = @$"{AppDomain.CurrentDomain.BaseDirectory}\{_appOptions.Directories.GeneratedCode}\RuleCompillerGeneratedValidator.cs";
            System.IO.File.WriteAllText(pathGenerateCode, purchase.GeneratedCode.Code, Encoding.Default);

            string errors;

            var pathToDll = @$"{AppDomain.CurrentDomain.BaseDirectory}\RuleCompiller.dll";
            Assembly asm = Assembly.LoadFrom(pathToDll);
            Type? t = asm.GetType("RuleCompiller.GeneratedValidator");
            MethodInfo? square = t.GetMethod("BeforeCheck");
            object? result = square?.Invoke(null, new object[] { });
            errors = result.ToString();

            if (string.IsNullOrEmpty(errors))
            {
                return View();
            }
            else
            {
                List<string> errorsList = new List<string>();
                var errorrsXml = XElement.Parse(errors);
                foreach (var error in errorrsXml.XPathSelectElements("Error"))
                {
                    var reader = error.CreateReader();
                    reader.MoveToContent();
                    string errorText = reader.ReadInnerXml();
                    errorsList.Add(errorText);
                }

                if (errorsList.Count > 0)
                {
                    ViewBag.ErrorsList = errorsList;
                    ViewBag.Purchase = purchase;
                    return View("ErrorPurchase");
                }
                else
                {
                    return View();
                }
            }
        }

        [HttpPost]
        [Route("Purchase/CreatePurchase/{id?}")]
        public IActionResult CreatePurchase(Field[] fields, int purchaseId)
        {
            XDocument fieldsXml = new XDocument();
            XElement fieldsInfo = new XElement("root");
            foreach (Field field in fields)
            {
                fieldsInfo.Add(new XElement(field.Alias, string.IsNullOrEmpty(field.Value) ? " " : field.Value));
            }
            fieldsXml.Add(fieldsInfo);

            var codes = db.ExecutableСodes.ToList();
            var fieldsForView = db.Fields.ToList();
            Purchase purchase = db.Purchases.Where(p => p.PurchaseId == purchaseId).FirstOrDefault();

            if (!Directory.Exists($@"{AppDomain.CurrentDomain.BaseDirectory}\{_appOptions.Directories.GeneratedCode}"))
            {
                Directory.CreateDirectory(@$"{AppDomain.CurrentDomain.BaseDirectory}\{_appOptions.Directories.GeneratedCode}");
            }

            var pathGenerateCode = @$"{AppDomain.CurrentDomain.BaseDirectory}\{_appOptions.Directories.GeneratedCode}\RuleCompillerGeneratedValidator.cs";
            System.IO.File.WriteAllText(pathGenerateCode, purchase.GeneratedCode.Code, Encoding.Default);

            var pathToDll = @$"{AppDomain.CurrentDomain.BaseDirectory}\RuleCompiller.dll";
            Assembly asm = Assembly.LoadFrom(pathToDll);
            Type? t = asm.GetType("RuleCompiller.GeneratedValidator");
            MethodInfo? square = t.GetMethod("AfterCheck");
            object? result = square?.Invoke(null, new object[] { fieldsXml });
            string errors = result.ToString();

            //string errors = GeneratedValidator.AfterCheck(fieldsXml.ToString());

            if (string.IsNullOrEmpty(errors))
            {
                return View("AcceptPurchase");
            }
            else
            {
                List<string> errorsList = new List<string>();
                var errorrsXml = XElement.Parse(errors);
                foreach (var error in errorrsXml.XPathSelectElements("Error"))
                {
                    var reader = error.CreateReader();
                    reader.MoveToContent();
                    string errorText = reader.ReadInnerXml();
                    errorsList.Add(errorText);
                }

                if (errorsList.Count > 0)
                {
                    ViewBag.ErrorsList = errorsList;
                    ViewBag.Purchase = purchase;
                    return View("ErrorPurchase");
                }
                else
                {
                    return View("AcceptPurchase");
                }

            }
            return View();
        }




    }
}

SAPR/Views/Purchase/AcceptPurchase.cshtml
@{ ViewData["Title"] = "Составление заявки";}

<!DOCTYPE html>
<html>
<head>
</head>
<body>
    <div class="row justify-content-center">
        <h1>Всё супер, заявка оформлена!</h1>
    </div>
    <div class="row justify-content-start">
        <a class="nav-link text-dark row justify-content-center" asp-area="" asp-controller="Purchase" asp-action="Index">
            <button type="submit" class="btn btn-primary">Сохранить</button>
        </a>
    </div>
</body>
</html>

SAPR/Views/Purchase/CreatePurchase.cshtml
@{ ViewData["Title"] = "Составление заявки";}

<!DOCTYPE html>
<html>
<head>
</head>
<body>
    <div>
        <h3>Форма оформления Заявки</h3>
        <p>Для оформления заявки заполните следующие поля:</p>
        <form method="post" class=" = " needs-validation">
            <div class="row g-3 p-3">
                @for (int i = 0; i < ViewBag.Purchase.Fields.Count; i++)
                {
                    <div class="col-sm-6">
                        <label class="form-label">@ViewBag.Purchase.Fields[i].Name</label>
                        <input name="fields[@i].Value" class="form-control" value="@ViewBag.Purchase.Fields[i].DefaultValue">

                        <div hidden="true">
                            <input name="fields[@i].Name" value="@ViewBag.Purchase.Fields[i].Name" /><br />
                            <input name="fields[@i].Alias" value="@ViewBag.Purchase.Fields[i].Alias" /><br />
                            <input name="fields[@i].FieldId" value="@ViewBag.Purchase.Fields[i].FieldId" /><br />
                        </div>


                    </div>
                }
            </div>
            <div hidden="true">
                <input name="purchaseId" value="@ViewBag.Purchase.PurchaseId" /><br />
            </div>
            <button type="submit" class="btn btn-primary">Сохранить</button>
        </form>
    </div>
</body>
</html>

SAPR/Views/Purchase/ErrorPurchase.cshtml
@{ ViewData["Title"] = "Составление заявки";}

<!DOCTYPE html>
<html>
<head>
</head>
<body>
    <div>
        <div class="row justify-content-center list-group">
            <h2>К сожалению, заявка не прошла проверку!</h2><br />
            <h3>Список оишбок:</h3><br>
        </div>
        <div class="row justify-content-start list-group">
            @foreach (var error in ViewBag.ErrorsList)
            {
                <div class="d-flex pt-3">
                    <svg class="bd-placeholder-img flex-shrink-0 me-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 32x32" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#007bff"></rect><text x="50%" y="50%" fill="#007bff" dy=".3em">32x32</text></svg>

                    <p class="pb-1 pl-2 mb-0 lh-sm border-bottom">
                        @error <br>
                    </p>
                </div>
            }
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="row py-lg-5">
            <div class="mx-auto">
                <p>
                    <a href="/Purchase/Index" class="btn btn-primary my-2">На главную</a>
                    <a href="/Purchase/CreatePurchase/@ViewBag.Purchase.PurchaseId" class="btn btn-secondary my-2">Редактировать</a>
                </p>
            </div>
        </div>
    </div>
</body>
</html>

SAPR/Views/Purchase/Index.cshtml
@model IEnumerable<Purchase>
@{ ViewData["Title"] = "Список доступных заявок";
}
<!DOCTYPE html>

<html>
<head>
    <title>Заявки</title>
</head>
<body>
    <h3>Доступные заявки</h3>
    <div>
        <ul class="list-group">
            @foreach (var purchase in Model)
            {
                <a href="/Purchase/CreatePurchase/@purchase.PurchaseId" class="" aria-current="true">
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        @purchase.Name
                        <span class="badge bg-primary rounded-pill text-white">@purchase.Fields.Count()</span>
                    </li>
                </a>
            }
        </ul>
    </div>  
</body>
</html>